MENTORING-T-45 제출
BI-kotlin-in-action/InGyuMoon pull request #1
Opened 2023-10-11 20:27 UTC by InGyu-Moon

감사합니다.

2023-10-12 01:53 UTC, konempty requested changes
고생하셨습니다 👍 
조금만더 수정 부탁드릴게요! ㅎㅎ

2023-10-12 01:53 UTC, konempty commented on boj_10870.kt
> +import java.util.*
헉 와일드 카드 임포트는 지양하는게 좋습니다
https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij
요 블로그 참고해서 설정해주세요!

2023-10-12 01:53 UTC, konempty commented on boj_10870.kt
> +    val num = scanner.nextInt()
scanner를 쓰실거라면 코틀린의 
```kotlin
readln().toInt()
```
를 사용하는게 좋습니다~!

2023-10-12 01:53 UTC, konempty commented on boj_10870.kt
> +    val arr = ArrayList<Int>()
코틀린에서는 arrayList보다는 mutableList를 주로 사용합니다~!

2023-10-12 01:53 UTC, konempty commented on boj_1978.kt
> +    // val num = readln().toInt()
오 요기는 제대로 쓰셨네요 ㅋㅋㅋ

2023-10-12 01:53 UTC, konempty commented on boj_1978.kt
> +    val reader = Scanner(System.`in`)
참고로 스캐너는 다쓰면 close를 해줘야합니다!

2023-10-12 01:53 UTC, konempty commented on boj_1978.kt
> +    for (i in 2..temp - 1) {
참고로 prime을 증명할때는 루트까지만 찾으면 됩니다 ㅋㅋㅋ
아니면 에라토스테네스의 채를 써보시면 좋구요

2023-10-12 01:53 UTC, konempty commented on boj_2178.kt
> +val distence = Array(101) { IntArray(101) { 0 } }
IntArray는 기본적으로 0으로 element들을 초기화 시켜주기 때문에 { 0 }은 무의미한 코드가 될것 같아요~!
그리고 변수명이 거리를 나타내는거라면 distance가 맞지않을까요? ㅎㅎ

2023-10-12 08:09 UTC, InGyu-Moon commented on boj_10870.kt
> +import java.util.*
블로그 글 읽어보겠습니다!

2023-10-12 08:09 UTC, InGyu-Moon commented on boj_10870.kt
> +    val num = scanner.nextInt()
처음에 readln().toInt()로 입력을 받았더니 백준에서 [런타임 에러 (NumberFormat)]가 발생해서 Scanner 사용했습니다...

2023-10-12 10:40 UTC, InGyu-Moon commented on boj_1978.kt
> +    val reader = Scanner(System.`in`)
추가하겠습니다

2023-10-12 10:41 UTC, InGyu-Moon commented on boj_2178.kt
> +val distence = Array(101) { IntArray(101) { 0 } }
IntArray가 기본적으로 0으로 초기화 시켜주는걸 몰랐습니다.
distance 고치겠습니다..ㅋㅋ

2023-10-12 11:00 UTC, konempty commented on boj_10870.kt
> +    val num = scanner.nextInt()
<img width="1252" alt="스크린샷 2023-10-12 오후 7 59 52" src="https://github.com/BI-kotlin-in-action/InGyuMoon/assets/44064530/848540cb-a4ec-4a70-bcbb-239f648ef768">
엇 아니예요..! 잘 작동합니다

2023-10-14 06:04 UTC, konempty requested changes
조금만더 수정 부탁드리구요
Scanner를 사용하는 코드를 전부 readln으로 바꿔주세요!

2023-10-14 06:04 UTC, konempty commented on boj_2178.kt
> +    var str = ArrayList<String>()
mutableList를 사용하는게 어떨까요??

2023-10-14 06:04 UTC, konempty commented on boj_2178.kt
> +        que.remove()
큐 가장 앞 요소를 가져오고 삭제하려면
```kotlin
val element = que.poll()
val a: Int = element.first
val b: Int = element.second
```
이 좋습니다~!

2023-10-14 12:30 UTC, InGyu-Moon commented on boj_10870.kt
> +    val num = scanner.nextInt()
제가 백준 1978번을 먼저 풀었었는데, 1978의 경우 공백을 기준으로 입력을 받아서 런타임 에러 (NumberFormat)가 발생했던것 같습니다. 그래서 10870 문제는 readln().toInt()으로 변경을 했는데 나머지 2문제에서 공백을 기준으로 입력을 받는 경우가 있는데 이런 경우에는
 `
val scanner = Scanner(System.`in`)
n = scanner.nextInt()
m = scanner.nextInt()
`
이렇게 Scanner를 사용하는 방법 대신
`
val input = readln().split(" ").map { it.toInt() }
n = input[0]
m = input[1]
`
 이렇게 작성해야 하나요?

2023-10-14 12:32 UTC, InGyu-Moon commented on boj_2178.kt
> +    var str = ArrayList<String>()
변경했습니다!

2023-10-14 12:33 UTC, InGyu-Moon commented on boj_2178.kt
> +        que.remove()
해당 방법으로 작성하겠습니다!

2023-10-14 13:41 UTC, konempty commented
<img width="337" alt="스크린샷 2023-10-14 오후 10 40 28" src="https://github.com/BI-kotlin-in-action/InGyuMoon/assets/44064530/12ad8d20-a0c2-4be0-8796-b28adeb1e2a6">
리뷰 받은 내용을 적용한후 다시 리뷰 요청을 해주셔야 제가 리뷰해도 되는지 알수 있습니다!

2023-10-14 13:49 UTC, konempty requested changes
진짜 조금만더 수정부탁드립니다!

2023-10-14 13:49 UTC, konempty commented on boj_10870.kt
> +}
<img width="254" alt="스크린샷 2023-10-14 오후 10 43 19" src="https://github.com/BI-kotlin-in-action/InGyuMoon/assets/44064530/0036189f-09b2-477d-b9df-6551de28f24f">

파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-10-14 13:49 UTC, konempty commented on boj_1978.kt
> +         * reader.nextInt()를 사용했습니다.
코드의 개선이 필요합니다
```kotlin
    val numbers: List<Int> = readln().split(" ").map{it.toInt()}
    for(number in numbers){
        if (isPrime(temp)) {
            cnt++
        }
    }
```
이렇게 해보면 아마 에러 없이 처리가 될것 같습니다~!

2023-10-14 13:49 UTC, konempty commented on boj_2178.kt
> +    val input = readln().split(" ").map { it.toInt() }
여기 제가 딱 원하는 코드를 이미 사용중이셨군요 ㅋㅋㅋㅋ

2023-10-15 07:40 UTC, konempty commented on boj_10870.kt
> +    val num = scanner.nextInt()
요걸 지금봤네요 ㅋㅋㅋ
네넵 맞습니다!

2023-10-16 14:07 UTC, InGyu-Moon commented on boj_1978.kt
> +         * reader.nextInt()를 사용했습니다.
알겠습니다~!

2023-10-16 14:11 UTC, InGyu-Moon commented on boj_10870.kt
> +}
다른글들도 읽어봤는데 개행을 하는게 표준이니깐 마지막에 꼭 엔터를 쳐주자 정도로 이해를 하면될까요??

2023-10-16 14:31 UTC, konempty commented on boj_10870.kt
> +}
네네 맞습니다 그런데 매번 신경쓰기 귀찮으니 ide에 설정을 넣어서 자동으로 들어가도록 하자는 의도입니다~!

2023-10-16 14:42 UTC, konempty approved these changes
크 고생하셨습니다 👍 👍 
리뷰가 너무 길어지는것 같아서 코멘트는 요정도만 드리고
더 고급내용은 나중에 어려운 내용 배우면 그때 알려 드릴게요!
요번 코멘트 내용 반영후 머지하셔도 좋습니다 :)

2023-10-16 14:42 UTC, konempty commented on boj_1978.kt
> +    val reader = Scanner(System.`in`)
어.... 요 스캐너 이제 필요없지 않나요..?

2023-10-16 14:42 UTC, konempty commented on boj_1978.kt
> +import java.lang.Math.sqrt
자바 math의 sqrt를 쓰는것 보단 코틀린의 내장 sqrt를 쓰는게 더 낫습니다~!

2023-10-16 14:42 UTC, konempty commented on boj_1978.kt
> +    val num = readln().toInt()
요 num은 이제 쓸모가 없어졌군요 ㅋㅋㅋ 굳이 변수에 담지 않아도 좋아보입니다!

2023-10-16 14:42 UTC, konempty commented on boj_1978.kt
> +        }
요코드를 더 줄이자면 코틀린에서는 컬렉션에서 조건에 맞는 원소들의 개수를 새주는 count라는 함수가 존재합니다!
따라서 아래와 같이 최적화가 가능합니다 ㅋㅋㅋ
```kotlin
    val cnt = readln().split(" ").map { it.toInt() }.count { isPrime(it) }
```

여기서 람다까지 사용하면 아래와 같이 더 줄일수 있습니다
```kotlin
    val cnt = readln().split(" ").map { it.toInt() }.count(::isPrime)
```

2023-10-16 14:42 UTC, konempty commented on boj_2178.kt
> +        str.add(temp)
굳이 temp에 한번 넣어서 배열에 삽입하는 이유가 있을까요??

2023-10-16 14:42 UTC, konempty commented on boj_10870.kt
> +    var temp: Int
여기서 var로 선언해서 가변성을 노출하는것 보단 아래 포문 블럭 안에서만 유효한 val temp = ~~가 더 나을것 같습니다!

2023-10-17 08:13 UTC, InGyu-Moon commented on boj_1978.kt
> +import java.lang.Math.sqrt
위 스캐너도 지우고 sqrt도 수정했습니다!

2023-10-17 08:14 UTC, InGyu-Moon commented on boj_1978.kt
> +    val num = readln().toInt()
요것도 지우겠습니다!

2023-10-17 08:18 UTC, InGyu-Moon commented on boj_2178.kt
> +        str.add(temp)
제가 코테 공부를  c++로 해서 c++에서는 저런 형식으로 많이 사용했었는데, 좀 찾아보니깐 
`val temp = readln()
str.add(temp)` 해당 코드 대신 `str.add(readln()) 이렇게 작성하면 될까요??
`

2023-10-17 08:20 UTC, InGyu-Moon commented on boj_10870.kt
> +    var temp: Int
수정하겠습니다!

2023-10-17 08:36 UTC, InGyu-Moon commented on boj_1978.kt
> +        }
음 처음 보는 기능이라 신기하네요 이것도 적용 시키겠습니다.

2023-10-17 08:40 UTC, merged

2023-10-17 12:31 UTC, konempty commented on boj_2178.kt
> +        str.add(temp)
네네 그렇게 하시거나 temp라는 변수명을 좀더 명시적인 이름으로 지어주시는게 좋을것 같아요!

2023-10-17 13:01 UTC, InGyu-Moon commented on boj_2178.kt
> +        str.add(temp)
넵 감사합니다!