MENTORING-T-61 제출
BI-kotlin-in-action/InGyuMoon pull request #2
Opened 2023-10-31 22:26 UTC by InGyu-Moon

오늘 00시까지 제출이였는데 늦어서 죄송합니다.
시험 끝나고 정신이 없어서 스페이스 확인도 못하고 스페이스도 잘 확인하겠습니다..!!
감사합니다.

2023-11-01 10:58 UTC, konempty requested changes
고생하셨습니다 👍 👍 
조금만더 수정 부탁드리구요
저희 이번주 문제 풀이는 최소 4문제, 최대 7문제까지 올리셔야 합니다!
한문제 더 풀어서 올려주세요 :)

2023-11-01 10:58 UTC, konempty commented on boj_1026.kt
> +    b.sortDescending()
inputA inputB를 바로 소팅해도 되지않을까요??

2023-11-01 10:58 UTC, konempty commented on 프로그래머스_요격시스템.kt
> +    //vec.sort()를 사용해도 똑같은거 아닌가요??
요 질문의 의도가 이해가 안되는데
아래 코드가 뭔가 다르게 작동해서 그렇게 작성하신거 아니신가요..?

2023-11-01 10:58 UTC, konempty commented on boj_1026.kt
> +    }
저라면 요 4줄의 코드를 아래와 같이 1줄로 작성할것 같아요!

```kotlin
val sum = a.zip(b).sumOf{(it1, it2)-> it1 * it2}
```

2023-11-01 10:58 UTC, konempty commented on boj_10836.kt
> +    //vec과 같은 고정(?) 2차원 배열은 mutableList 대신 Array를 사용해도되나요?
오히려 mutableList를 쓰면 불필요한 가변성을 노출시키는 코드가 되기때문에
어레이가 맞습니다~!

2023-11-01 10:58 UTC, konempty commented on boj_10836.kt
> +    val vec = Array(n) { IntArray(3) }
3개의 자료만 담는 자료형으로 코틀린에는 Triple이라는 클래스가 있습니다~!

2023-11-01 10:58 UTC, konempty commented on 프로그래머스_요격시스템.kt
> +    vec.sortBy { it[1] }
0과 1 딱 두개의 인덱스만 사용하는것 같은데
그렇다면 코틀린의 Pair라는 클래스를 사용하는게 좋습니다~!

2023-11-01 15:16 UTC, InGyu-Moon commented on 프로그래머스_요격시스템.kt
> +    //vec.sort()를 사용해도 똑같은거 아닌가요??
`vec.sortBy { it[0] } vec.sortBy { it[1] }` 이 코드와  `vec.sort()` 이 코드의 결과를 출력해봤는데 똑같이 나오던데 `vec.sort()` 로 제출하면 정답이 틀려서 질문드렸습니다.

2023-11-01 15:25 UTC, InGyu-Moon commented on boj_1026.kt
> +    b.sortDescending()
리스트는 소팅이 안되길래 따로 mutableList를 만들었었는데 수정했습니다!

2023-11-01 15:29 UTC, InGyu-Moon commented on boj_1026.kt
> +    }
아직 람다식이 안익숙한것같습니다. 수정해보겠습니다.

2023-11-01 15:35 UTC, InGyu-Moon commented on boj_10836.kt
> +    val vec = Array(n) { IntArray(3) }
Triple로 변경을 해볼라 했는데 변경을 하면 아래 for문에서 j의 인덱스에 접근이 힘들것 같은데 IntArray(3)로 사용해도 되나요?  코드에 위치 주석으로 남겨 놓았습니다.

2023-11-02 11:53 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
요번 코멘트만 반영하시고 머지하시면 될것 같습니다~!
그리고 한가지 코멘트를 드리자면 다음 커밋부터는 
커밋 메시지를 좀더 의미를 담아서 지어주세요 ㅎㅎ...

2023-11-02 11:53 UTC, konempty commented on boj_2217.kt
> +    mutableList.sortDescending()
sort를 해야한다면 mutableList 대신에 sortedSet을 사용하고 정렬 조건을 역으로 주시는게 좋을것 같습니다~!

2023-11-02 11:53 UTC, konempty commented on 프로그래머스_요격시스템.kt
> +    //vec.sort()를 사용해도 똑같은거 아닌가요??
vec.sort()가 실행이 되나요??
IntArrat는 comparable이 아니라서 아마 에러가 날것 같아요..!
그래서 개발자가 직접 sortedBy로 정렬 조건을 명시해줘야 할거예요

<img width="1612" alt="스크린샷 2023-11-02 오후 8 46 01" src="https://github.com/BI-kotlin-in-action/InGyuMoon/assets/44064530/89701a48-36ff-4e4a-a880-d86fde7428bf">

2023-11-02 11:53 UTC, konempty commented on boj_1026.kt
> +    inputB.sortDescending()
여기도 sortedSet을 쓰는게 더 좋을것 같아요!

2023-11-02 11:53 UTC, konempty commented on boj_10836.kt
> +    val vec = Array(n) { IntArray(3) }
아하 그런 이유라면 괜찮을것 같네요 ㅋㅋㅋ

2023-11-02 16:03 UTC, InGyu-Moon commented on boj_1026.kt
> +    inputB.sortDescending()
sortedSet은 현재 배열을 정렬하는게 아니라 새로운 배열을 리턴하는거라서 새로운 list를 만들어야 되던데 새로운 list를 만드는것보단 sort를 사용하는게 더 좋지 않나요??

2023-11-02 16:06 UTC, merged